tap "xwmx/taps"
brew "direnv"
brew "chruby"
brew "fzf"
brew "git"
brew "gh"
brew "gmp" # dependecy of ruby
brew "graphviz"
brew "jq"
brew "nb"
brew "neovim"
brew "qt"
brew "ripgrep"
brew "ruby-install"
brew "tig"
brew "tmux"
brew "tree"
brew "yarn"
brew "zsh"

# cask
cask_args appdir: "/Applications"
tap "homebrew/homebrew-cask"
tap "homebrew/cask-fonts"
cask "docker"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "http-toolkit"
cask "iterm2"
cask "postgres"
cask "rectangle"
cask "rowanj-gitx"
cask "visual-studio-code"
